export interface Customer {
   customerId: number
   customerCode: string
   oldCustomerCode: string
   name: string
   companyRegNum: string
   taxNum: any
   currencyId: number
   stateId: number
   countryId: number
   paymentMethodId: number
   locationId: number
   bankAcct: any
   controlAccountId: number
   salesAgentId: number
   termPeriodId: number
   creditLimit: any
   overDueLimit: any
   outstanding: any
   allowExceedCreditLimit: boolean
   addPDLimit: boolean
   agingOn: boolean
   statementType: any
   billDescription: any
   billEmail: any
   billPhone: any
   billFax: any
   billAddress: string
   billPostCode: any
   billContact: any
   billAreaId: number
   billAttention: any
   shipDescription: string
   shipEmail: any
   shipPhone: any
   shipFax: any
   shipAddress: string
   shipPostCode: any
   shipContact: any
   shipAreaId: number
   shipAttention: any
   customerUDField1: any
   customerUDField2: any
   customerUDField3: any
   customerUDOption1: any
   customerUDOption2: any
   customerUDOption3: any
   logoFileId: any
   priceSegmentCode: string
   businessModelType: string
   supplyTaxId: number
   isPrimary: boolean
   isItemPriceTaxInclusive: boolean
   isDisplayTaxInclusive: boolean
   isUniversal: boolean
   sequence: number
   createdById: number
   createdBy: string
   createdAt: string
   modifiedById: number
   modifiedBy: string
   modifiedAt: string
   deactivated: boolean
}
